### ISSUE TITLE
[BACKEND] L'usage de l'API Back-for-Front

### ISSUE THREAD

**Issue by charafzellou** [MTthoas/Dex#39]
N'oubliez pas que votre service Backend sert votre Frontend, dans le sens où vos routes seront consommées par le Front.

La requête que vous implémentez pour l'instant récupère une liste de tokens de CoinGecko mais ne les formatte pas dans un format consommable par votre front (YAML, JSON ou autre)

**Comment by Guiiz94** [comment]
Ceci ne représente qu'une fonctionnalité de l'API
Elle retourne un JSON
