### ISSUE TITLE
[BC] Create contract: TokenManager

### ISSUE THREAD

**Issue by Ronfflex** [MTthoas/Dex#59]
Contract to manage the creation and listing of different tokens (ERC-20 or ERC-721 standards).

Create a function (listToken) that allows the contract owner or authorized administrators to list a new token on the platform.
This function should validate the token contract address, store the token information in the appropriate data structure, and emit an event for token listing.

Create a function (delistToken) that allows the contract owner or authorized administrators to delist a token from the platform.
This function should remove the token information from the appropriate data structure and emit an event for token delisting.

Create functions to retrieve information about listed tokens, such as token name, symbol, and other relevant metadata.
Provide functions to retrieve a list of all listed token addresses or IDs.

Don't forget to add Event, Error handling and Documentation.

**Comment by MTthoas** [comment]
Put screens in your futures PR approving your code and showing that features. 
For every features that can be cool

**Comment by Ronfflex** [comment]
![image](https://github.com/MTthoas/Dex/assets/65185673/fe4e3247-7449-4196-8650-ce53f8a1ec66)

More ideas of tests ?

**Comment by Ronfflex** [comment]
Used ERC-20 standard
